### ISSUE TITLE
.NET Core 3.0+ support

### ISSUE THREAD

**Issue by picolino** [DevExpress/DevExpress.Mvvm.Free#15]
Hello there.

Do you have any plans to support .NET Core WPF projects (accord .NET Core 3.0 release)?
Nowadays this warning I get every time I trying to build .NET Core WPF project:

`
warning NU1701: Package 'DevExpressMvvm 18.2.3' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.0'. This package may not be fully compatible with your project.
`

**Comment by AlexanderEgorov** [comment]
Hello,

Yes, it's planned after DevExpress v19.2 release which should be there soon.

**Comment by energycognito** [comment]
I'm still getting this on version 19.2.3: warning NU1701: Package 'DevExpress.Mvvm 19.2.3' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.0'. This package may not be fully compatible with your project.

**Comment by picolino** [comment]
@energycognito it's weird behaviour, my .NET Core WPF projects fully compatible with latest version of DevExpress.Mvvm package and no warnings shown.

**Comment by AlexanderEgorov** [comment]
Hi,

@energycognito, would you please provide a sample project demonstrating the issue? Please also clarify what Visual Studio version you use.
