### ISSUE TITLE
How to use IDialogService

### ISSUE THREAD

**Issue by Tdue21** [DevExpress/DevExpress.Mvvm.Free#8]
I am having a bit of trouble discovering the IDialogService. Is this not implemented in the free MVVM Framework? 
If not, is it possible to get an example how to do this?

**Comment by AlexanderEgorov** [comment]
Hello,
 
Our **DialogService** implementation is complex and is based on DevExpress components. That's why it is not included into a free MVVM version.
You can implement the **IDialogService** yourself or create a special view with the predefined view model to use them in your dialog window.
I have attached a sample to demonstrate both these approac
[IDialogServiceTest.zip](https://github.com/DevExpress/DevExpress.Mvvm.Free/files/1001029/IDialogServiceTest.zip)
hes.

**Comment by Tdue21** [comment]
Awesome, thanks. I will look into it. 👍 😄

**Comment by Tdue21** [comment]
Ok. I get how to show the dialog. But I do not get how to connect the UICommands with the dialog content? Based on the `IDialogServiceTest` you attached, I have implemented something that works with regard to showing a user control, and connecting the buttons on the CustomDialogService to commands on the user control's view model. 

E.g. I have a MainViewModel which calls my CustomDialogService implementation like this: 

  var result = CustomDialogService.ShowDialog(MessageButton.OKCancel, "Settings", "SettingsView");

`SettingsView` is a UserControl which is data bound to a `SettingsViewModel`. Different commands on this view model should be called depending on the buttons pressed on the dialog. 

Alternatively, it must be possible for the UserControl to interact with the containing CustomDialog. 

Thoughts, comments?

**Comment by AlexanderEgorov** [comment]
What about this?
```
var vm = new SettingsViewModel();
var okCommand = new UICommand();
okCommand.Command = new DelegateCommand(() => vm.OK());
var res = CustomDialogService.ShowDialog(new[] { okCommand }, "Settings", "SettingsView", vm);
```

**Comment by Tdue21** [comment]
Yes, that would work. It doesn't work very well with DI though. I would prefer that the view created the view model through DI but I see what you are aiming at. I'll consider it. 

Thanks again :)
