### ISSUE TITLE
Update free component to the 17.2.*?

### ISSUE THREAD

**Issue by Muhomorik** [DevExpress/DevExpress.Mvvm.Free#9]
Hello,

Can you update the components of the free version to the 17.2.7+ ?

I am using it to send code samples with problems (WPF component) to support teams of other components and it is convenient to just include nuget in the project.

Samples are not using DX components, but I can copy existing VM without any changes and bind to regular buttons and textBoxes/etc.

Unfortunately VS doesn't like 17.1 and 17.2 together :)

/ Best regards
Dmitri

**Comment by nocanstillbb** [comment]
Details about calling real-time (JIT) debugging instead of this dialog box,

See the end of this message.



************************** Abnormal Text****************************

System.ArgumentException:

Parameter name: args

In DevExpress. Mvvm. UI. Native. JumpAction ManagerClient. Run (String [] args, Action `1 startProcess) location C: Users Bing\ Desktop DevExpress. Mvvm. Free-master DevExpress. Mvm. UI. Application Jumper Launcher\ JumpionsManager. Clics: line number 271.

In DevExpress.Mvvm.UI.Application JumpTask Launcher.Program.Main (String[] args) location C: Users\ Bing Desktop\ DevExpress.Mvvvm.Free-master DevExpress.Mvvvm.UI.Application JumpTask Launcher\ Program.cs: line number 11




**************************** Loaded Assemblies********************

Mscorlib

Assembly version: 4.0.0.0

Win32 Version: 4.7.3221.0 Build by: NET472REL1LAST_C

Basic code: file://C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

--------------------------------------------------------------------------------------------------------------------------------------------

DevExpress. Mvvm. UI. Application JumpTask Launcher

Assembly version: 18.2.0.0

Win32 Version: 18.2.0.0

Basic code: file://C:/Users/Bing/Desktop/DevExpress.Mvvm.Free-master/Bin/Framework 4/DevExpress.Mvvvm.UI.Application JumpTask Launcher.exe

--------------------------------------------------------------------------------------------------------------------------------------------

System

Assembly version: 4.0.0.0

Win32 Version: 4.7.3190.0 Build by: NET472REL1LAST_C

Basic code: file://C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0_u b77a5c561934e089/System.dll

--------------------------------------------------------------------------------------------------------------------------------------------

System.Windows.Forms

Assembly version: 4.0.0.0

Win32 Version: 4.7.3221.0 Build by: NET472REL1LAST_C

Basic code: file://C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0_u b77a5c561934e089/System.Windows.Forms.dll

--------------------------------------------------------------------------------------------------------------------------------------------

System.Drawing

Assembly version: 4.0.0.0

Win32 Version: 4.7.3056.0 Build by: NET472REL1

Basic code: file://C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0_u b03f5f7f11d50a3a/System.Drawing.dll

--------------------------------------------------------------------------------------------------------------------------------------------

System.Core

Assembly version: 4.0.0.0

Win32 Version: 4.7.3221.0 Build by: NET472REL1LAST_C

Basic code: file://C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0_u b77a5c561934e089/System.Core.dll

--------------------------------------------------------------------------------------------------------------------------------------------

System.Configuration

Assembly version: 4.0.0.0

Win32 Version: 4.7.3056.0 Build by: NET472REL1

Basic code: file://C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0_u b03f5f7f11d50a3a/System.Configuration.dll

--------------------------------------------------------------------------------------------------------------------------------------------

System.Xml

Assembly version: 4.0.0.0

Win32 Version: 4.7.3056.0 Build by: NET472REL1

Basic code: file://C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0_u b77a5c561934e089/System.Xml.dll

--------------------------------------------------------------------------------------------------------------------------------------------

Mscorlib.resources

Assembly version: 4.0.0.0

Win32 Version: 4.7.3056.0 Build by: NET472REL1

Basic code: file://C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll

--------------------------------------------------------------------------------------------------------------------------------------------

System. Windows. Forms. Resources

Assembly version: 4.0.0.0

Win32 Version: 4.7.3056.0 Build by: NET472REL1

Basic code: file://C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.dll.

--------------------------------------------------------------------------------------------------------------------------------------------



************************ JIT Debugging**************************************

To enable real-time (JIT) debugging,

The system. windows. forms section of the application or computer's. config file (machine. config) must be set

JitDebugging value.

The application must also be enabled when compiling

Debugging.



For example:



<configuration>

<system.windows.forms jitDebugging="true"/>

</configuration>



Any unhandled exception after JIT debugging is enabled

Will be sent to the JIT debugger registered on this computer.

Instead of being handled by this dialog box.

**Comment by Muhomorik** [comment]
Hi, 
I am using 18.2.3, but 17.2 was the last version to get at that point of time.
I will close the ticket

/ Best regards.

**Comment by AlexanderEgorov** [comment]
I understand that are using DX components v17.1 and sometimes you want to extract certain ViewModels to a separate project with our Free MVVM.
But, I do not quite understand why you are not using the latest version of the Free MVVM. We are always trying to provide back-compatibility of our libraries, so there should not be any serious problems.
